name: Build and release

on: [push]

jobs:
  build_release:
    name: Build and release

    runs-on: windows-latest

    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for gitversion

      -
        name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install GitVersion CLI tool for upload artifact steps
        run: choco install GitVersion

      -
        name: Build solution
        run: msbuild chromodorisBV.sln /p:Configuration=Release -restore

      -
        id: get-semver
        name: Get SemVer version
        run: echo SEMVER=$(gitversion | jq --raw-output .SemVer) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chromodorisBV_${{ env.SEMVER }}
          path: artifacts/dist/*

      -
        name: Check Tag
        id: check-tag
        shell: bash
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      -
        name: Create release-zip
        id: create-zip
        if: steps.check-tag.outputs.match == 'true'
        run: >
          7z a -tzip
          artifacts\dist\ChromodorisBV_$Env:SEMVER.zip
          .\artifacts\dist\*

      -
        name: Create release on semver tag
        if: steps.check-tag.outputs.match == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: artifacts/dist/*
